name: nel
version: 0.0.1
author: Matthew Butler
description: Never Ending List - The Awesome Marcato Hackaton App.
dependencies:
  browser: '>=0.10.0+2 <0.11.0'
  core_elements: any
  crypto: any
  paper_elements: any
  polymer: any
transformers:
- polymer:
    entry_points: web/index.html
